### ISSUE TITLE
Umbrella Docker Tasklist

### ISSUE THREAD

**Issue by doctyper** [nfl/react-wildcat#142]
Create a Wildcat Docker container that includes the following:

### Outstanding
- [ ] Required global dependencies
  - [ ] Node 4.x
  - [ ] npm 3.x
  - [ ] jspm 0.16.x
- [ ] Required local dependencies
  - [ ] node_modules
  - [ ] jspm_packages

### Wishlist
- [ ] Host / maintain a development TLD (e.g. `.dev`, `.localhost`) within a Docker container

**Comment by staxmanade** [comment]
Just a thought in the tld https://iyware.com/dont-use-dev-for-development/

**Comment by doctyper** [comment]
@staxmanade Yeah we are in the process of switching TLDs.
