### ISSUE TITLE
Documentation Umbrella Task

### ISSUE THREAD

**Issue by jamsea** [nfl/react-wildcat#162]
This was started in PR #140. I think it makes sense to split this up so we don't feel overwhelmed. 

A good first step is to get a README.md file in each of wildcat's smaller packages. We've already finished a few of them:
- [x] react-wildcat-ensure
- [ ] react-wildcat-handoff
- [ ] react-wildcat-hot-reloader
- [x] react-wildcat-prefetch
- [ ] react-wildcat-test-runners

https://github.com/nfl/react-wildcat/tree/master/packages/react-wildcat-prefetch is a great example of what we need for each of these projects. Just a markdown file explaining what the project is and an example of how to use it.

PR #140 introduces gitbook support which makes for some nicely formatted docs.

**Comment by Toughee** [comment]
Hello @jamsea Is the issue still available to be resolved? I can look into resolving it if possible.

**Comment by jamsea** [comment]
I don’t have merge permissions on this repo anymore. @miblanchard are y’all still maintaining this anymore or did you switch to NextJs?

**Comment by miblanchard** [comment]
@Toughee @jamsea - This is now deprecated and no longer in use by our team.  

I have not looked at this in a while, but I am adding a note to the README about deprecation.

**Comment by Toughee** [comment]
@miblanchard Alright. Thank you for letting us know
